name: Build, Push and Deploy

on:
  workflow_call:
    secrets:
      GIT_CREDENTIALS:
        required: true
    inputs:
      ORG_NAME:
        description: 'GitHub organization name'
        required: true
        type: string
      REPO_NAME:
        description: 'Repository name for Docker image'
        required: true
        type: string
      ENV_NAME:
        description: 'Environment name for deployment'
        required: true
        type: string

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short commit SHA
        id: vars
        run: |
          echo "COMMIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            GIT_CREDENTIALS=${{ secrets.GIT_CREDENTIALS }}
          push: true
          tags: |
            ghcr.io/${{ inputs.ORG_NAME }}/${{ inputs.REPO_NAME }}:${{ github.ref_name }}
            ghcr.io/${{ inputs.ORG_NAME }}/${{ inputs.REPO_NAME }}:${{ env.COMMIT_SHA }}

      - name: Update image in deployment
        run: |
          sed -i "/##-image-replacer-##$/c\          image: ghcr.io/${{ inputs.ORG_NAME }}/${{ inputs.REPO_NAME }}:${{ env.COMMIT_SHA }} ##-image-replacer-##" deployment/overlays/${{ inputs.ENV_NAME }}/deployment.yaml

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions Testnet Deploy"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git add deployment/overlays/${{ inputs.ENV_NAME }}/deployment.yaml
          git commit -m "Update deployment image to use commit ${{ env.COMMIT_SHA }}"
          git push

      - name: Set output
        run: echo "COMMIT_SHA=${{ env.COMMIT_SHA }}" >> $GITHUB_ENV
